<p style="background:#f4f4f4; padding:5px; margin-left:-5px;margin-bottom:0px">
Informática - 1º de Física
<br>
<strong>Introducción a la Programación</strong>
</p>

## Tema 2. Instrucciones de control

### Motivación

En el tema anterior hemos aprendido a programar el cálculo de operaciones numéricas usando signos del teclado que tratan de imitar el lenguaje matemático tradicional. El aspecto que tiene el código no es muy atractivo pero cumple con su cometido de definir con precisión las operaciones deseadas.

Además, hay dos características importantes que permiten una forma rudimentaria de programación:

- Podemos escribir una secuencia de instrucciones, tan larga como queramos, para que se efectúen una detrás de otra.

- Se pueden redefinir los nombres (o dicho de otra manera, reasignar nuevos valores a las variables).

Con esto ya podríamos resolver problemas sencillos como p. ej. extraer una raíz cuadrada mediante aproximaciones sucesivas. Copiando y pegando líneas podemos escribir algo como:

In [1]:
n = 121

x = 3
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2
x = (x + n/x)/2

x

11.0

El resultado es exacto. Sin embargo, el código anterior tiene varios inconvenientes: uno muy importante es que el número de refinamientos que hay que hacer depende de $n$ y del valor inicial de $x$. Seguramente aquí sobran repeticiones (se puede añadir un `print(x)` después de cada paso para ver el progreso del cómputo) pero en otros casos podrían faltar.

Lo peor de todo es que el código tiene una pinta horrible.  Aunque nunca hayamos visto nada de programación una repetición literal de instrucciones como la anterior causa una malísima impresión. Imagina un problema que necesite miles de pasos para alcanzar una solución aceptable.

### Control de flujo

Los lenguajes de programación tienen **construcciones de control** para especificar cuántas veces o en qué condiciones hay que efectuar un cierto grupo de instrucciones. Hay varios tipos, que podemos estructurar así:

- selección (`if`)
    
- repetición

    - general (`while`)
    
    - bucle   (`for`)
    

En primer lugar vamos a explicar brevemente su funcionamiento y luego las emplearemos para expresar mejor el cálculo anterior. Usaremos la palabra **bloque** para indicar una secuencia cualquiera de instrucciones.

La sentencia `if` efectúa un bloque u otro dependiendo de una condición lógica:


In [2]:
if 5*7 > 40:
    print('qué bien')
else:
    print('mala suerte')
    print('adiós')

mala suerte
adiós


La sentencia `while` sirve para repetir un bloque mientras se cumple una condición lógica. Como ejemplo sencillo, el siguiente código va duplicando un número sucesivas veces mientras sea menor que 100.

In [3]:
z = 1

while z < 100:
    z = 2*z

z

128

El ordenador "no sabe" el número de repeticiones que se van a realizar. Si el bloque está mal programado es posible que nunca deje de cumplirse la condición y el ordenador se quede "colgado". (Si esto ocurre se puede interrumpir el proceso en la opción de menú "Kernel->Interrupt".)

Finalmente, la sentencia `for` sirve para repetir un bloque recorriendo un conjunto de valores. Es uno de los conceptos más importantes en programación, conocido  como _iteración_ o _bucle_.  

In [4]:
for x in [5, 11, 27]:
    print( 2*x+5 )

15
27
59


Muchas veces los bucles recorren secuencias de enteros:

In [5]:
for k in range(4):
    print('hola', k)

hola 0
hola 1
hola 2
hola 3


Hay que elegir un nombre (cualquiera, aunque se suele usar `k`, `j` , etc.) para el llamado "índice del bucle", que irá tomando valores sucesivos en cada una de las repeticiones.

En Python y muchos otros lenguajes de programación se empieza a contar por cero. Aunque parezca extraño esto tiene [algunas ventajas](https://en.wikipedia.org/wiki/Zero-based_numbering) para trabajar con subíndices.

En las construcciones de control:

- es obligatorio poner `:` al final la sentencia.
    
- los bloques deben escribirse a partir de la línea siguiente, dejando 4 espacios de separación (que puedes conseguir con la tecla Tab).

- Los bloques pueden contener a su vez otras construcciones de control, formando una estructura de múltiples niveles.

- En cualquier momento podemos terminar de forma anticipada los bucles `for` y `while` mediante una sentencia `break`.

### Secuencias numéricas

Para construir secuencias de enteros se utiliza `range`. Para construir secuencias de números reales se utiliza `np.arange` y `np.linspace`. Estas secuencias se pueden recorrer con bucles `for` o utilizarlas para otros fines.

In [6]:
list(range(5))

[0, 1, 2, 3, 4]

In [7]:
list(range(2,10,3))

[2, 5, 8]

In [8]:
import numpy as np

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [11]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Caso de estudio

Veamos ahora algunas formas de calcular la raíz cuadrada por aproximaciones sucesivas usando estas herramientas. La primera idea es simplemente refinar la aproximacion un número fijo de veces:

In [12]:
n   = 121   # queremos extraer la raíz cuadrada de este número
x   = 3     # partimos de un valor cualquiera
rep = 5     # número de pasos

for _ in range(rep):
    x = (x + n/x)/2

x

11.000000367455819

(Hemos llamado `_` al índice del bucle indicando con ello que no lo vamos a usar. )

Si queremos observar la evolución de las aproximaciones añadimos un `print` dentro del bloque que se repite. En este caso sí usamos el índice, que llamamos por ejemplo `k`:

In [13]:
n   = 300
x   = 3
rep = 6

for k in range(rep):
    print(f'paso {k}: x = {x}')
    x = (x + n/x)/2

print('\nSolución:', x)

paso 0: x = 3
paso 1: x = 51.5
paso 2: x = 28.6626213592233
paso 3: x = 19.56460731776899
paso 4: x = 17.4492093914502
paso 5: x = 17.320982711195377

Solución: 17.320508082191836


<p style='margin-left:2cm; color:#555'><small>

Para que quede más bonito hemos usado una cadena con formato, que sirve para insertar valores numéricos dentro de una cadena de caracteres en los "huecos" indicados con `{}`. El código `\n` significa pasar al renglón siguiente.

</small></p>

Los dos últimos pasos tienen 5 cifras significativas iguales. No está mal, pero el proceso debe continuar unos cuantos pasos más si queremos que todos los decimales disponibles en el tipo `float` sean correctos.

Un bucle `for` no es lo ideal para este problema porque en principio desconocemos el número de iteraciones adecuado. Podríamos poner un número muy grande para asegurar un resultado aceptable pero no tiene mucho sentido hacer trabajo innecesario. 
Lo ideal es refinar la solución hasta conseguir la precisión deseada. Esto puede conseguirse fácilmente mediante la sentencia `while`. Una primera idea podría ser la siguiente:

In [14]:
n   = 121
x   = 3

while x**2 != n:
    print(x)
    x = (x + n/x)/2

x

3
21.666666666666668
13.625641025641027
11.25297858583519
11.00284361000081
11.000000367455819
11.000000000000007


11.0

El resultado es exacto (al menos en este caso) y el proceso iterativo termina cuando conseguimos la solución. Este código es un buen ejemplo del uso de `while`, pero desde el punto de vista del cálculo numérico tiene varios problemas:

- Hemos puesto una condición de igualdad estricta para detener la repetición. Esto es muy arriesgado al trabajar con números reales aproximados. Por ejemplo, si repetimos el proceso con $n=300$ el ordenador se quedará colgado: llega un momento en el que las aproximaciones se estabilizan en `17.32050807568877`, cuyo cuadrado es `299.99999999999994`.

- La condición de parada establecida es, directamente, encontrar la solución, no que el proceso iterativo deje de progresar. Es mejor realizar la iteración hasta que la aproximación converja y luego verificar que es una solución correcta.

Una versión mejorada es la siguiente. Haremos una repetición infinita con una condición de terminación `break` en medio del bloque. Para poder comparar una aproximación con la siguiente necesitamos dos variables: `x` es la anterior, y `xs` la nueva.

In [15]:
n   = 300
x   = 3
eps = 1E-6

while True:
    print(x)
    xs = (x + n/x)/2
    if abs(xs-x) < eps:
        break
    x = xs

print()
print(xs)
print(xs**2)

3
51.5
28.6626213592233
19.56460731776899
17.4492093914502
17.320982711195377
17.320508082191836

17.32050807568877
299.99999999999994


Observa que hay dos errores en juego: el error en la solución y el error en la condición que se debe cumplir.

En muchos procesos iterativos es conveniente poner también un límite en el número de pasos.

### Bucle acumulador

Veamos algún ejemplo más de bucle `for`. Intenta adivinar lo que va a ocurrir al evaluar las siguientes celdas sin mirar más adelante:

In [ ]:
for k in range(100):
    print(k,'al cuadrado es',k**2)

La anterior no tiene ningún misterio, simplemente se muestran muchos mensajes consecutivos sin ningún otro "efecto secundario". El siguiente caso no es tan inmediato:

In [17]:
b = 1
for k in range(10):
    b = b*3
b

59049

Redefinir `b` usando su valor anterior hace que sea difícil analizar lo que va a ocurrir. Afortunadamente este caso es muy simple. Podemos "desenrollar el bucle" mentalmente y darnos cuenta de que b va a ir valiendo sucesivamente:

    1
    1*3
    1*3*3
    1*3*3*3
    ...
    1*3*3*... 10 veces ... *3

Este tipo de operación es tan frecuente en programación que se inventaron operadores especiales como `+=` , `*=`, etc. para modificar variables.

In [18]:
b = 1
for k in range(10):
    b *= 3
b

59049

En la página [pythontutor](http://pythontutor.com/live.html#mode=edit) hay una herramienta interactiva para observar la evolución de un programa paso a paso. Es muy instructivo probarla con el trozo de código anterior.

Esta estructura de programación es muy común y permite expresar operaciones como sumas o productos del tipo

$$\sum_{k=a}^b f(k)$$

Siempre se hace igual: se usa una variable de acumulación que inicialmente vale 0 (ó 1 si es un producto, o en general el elemento neutro de la operación "acumuladora"), y mediante un bucle se van añadiendo términos:

    s = 0
    for k in range(a,b+1):
        s += f(k)

Propondremos algún ejercicio para practicar esta idea, aunque pronto veremos una forma más elegante de abordar este tipo de problemas.

### Ejercicios

- Modifica la resolución de la ecuación de segundo grado para comprobar si tiene soluciones reales.


- Haz una tabla de conversión de grados Fahrenheit a Celsius, de $32F$ hasta $212F$.



- Escribe un programa que imprima todos los divisores propios de un número.



- Calcula mentalmente la secuencia de números que imprimirá el siguiente código (el orden es importante):

        for i in range(5):
            for j in range(5):
                print(i+10*j)
            

- Imprime las tablas de multiplicar.


- Comprueba en unos cuantos casos que la suma de los $n$ primeros números impares es igual a $n^2$. Por ejemplo:

        1+3+5     = 3*3 = 9
        1+3+5+7+9 = 5*5 = 25
        ...

 $$ \sum_{k=0}^{n-1} (2k+1) = \sum_{k=1}^n (2k-1) = n^2 $$


- Calcula $7! = 7\times6 \times \ldots \times 2 \times 1$ mediante un bucle.


- Escribe un programa para calcular:

 $$\sum_{k=10}^{30} (2k^3-k^2+5k)$$


- Calcula numéricamente la probabilidad de que en un grupo de $n$ personas al menos dos de ellas cumplan años el mismo día ([Birthday problem](https://en.wikipedia.org/wiki/Birthday_problem)). (Problema explicado en la asignatura de Métodos Matemáticos I).


- Compara el factorial exacto con la [aproximación de Stirling](https://en.wikipedia.org/wiki/Stirling%27s_approximation) para $10!$, $20!$, ... $100!$.


- Escribe un programa para calcular el máximo común divisor de dos números mediante el algoritmo de [divisiones sucesivas](https://en.wikipedia.org/wiki/Euclidean_algorithm#Euclidean_division).



- Escribe un programa que calcule la raíz cúbica de un número mediante aproximaciones sucesivas. Intenta hacerlo modificando el método usado para la raíz cuadrada. Echa un vistazo al [método de Newton](https://en.wikipedia.org/wiki/Newton%27s_method).