# Sesión 2

Alumno: **Nombre Apellido Apellido**

Fecha: 28/30/1 de septiembre de 2020

### Calculadora

Voy a evaluar algunas operaciones de prueba...

In [1]:
import numpy as np

In [2]:
2+3

5

In [3]:
np.sin(np.radians(30))

0.49999999999999994

etc...

Ponemos nombres a los datos

In [4]:
b = 2+3

print(b)

c = 5*b+3

print(c)

5
28


### Razón áurea

Calcula 

$$\frac{1+\sqrt{5}}{2}$$

In [5]:
# mal
1  +  5**0.5 / 2

2.118033988749895

In [6]:
(1+5**(1/2)) / 2

1.618033988749895

In [7]:
(1+5**0.5) / 2

1.618033988749895

In [8]:
g = ( 1+np.sqrt(5) ) / 2
g

1.618033988749895

In [9]:
(1+g)/g

1.618033988749895

### Ecuación de segundo grado

Resuelve una ecuación de segundo grado

$$ax^2+bx+c=0$$

para

In [10]:
a = 2
b = -6
c = 4

x1 = (-b + (b**2-4*a*c)**0.5) / 2/a
x2 = (-b - (b**2-4*a*c)**0.5) / (2*a)

print(x1,x2)

# comprobamos
x = x1
print(a*x**2 + b*x + c)
x = x2
print(a*x**2 + b*x + c)

2.0 1.0
0.0
0.0


### Identidad de Euler

In [11]:
(-4)**0.5

(1.2246467991473532e-16+2j)

La parte real es un "cero numérico" (un número más pequeño que la precisión de los números reales aproximados que tiene el ordenador).

In [12]:
np.pi

3.141592653589793

In [13]:
np.e

2.718281828459045

Verfica 

$$e^{i \pi} + 1 = 0$$

In [14]:
np.exp(1j*np.pi) + 1

1.2246467991473532e-16j

In [15]:
np.e**(1j*np.pi) + 1

1.2246467991473532e-16j

Es aproximadamente cero.

### Peculiaridades de la coma flotante

Los números reales en informática son aproximados:

In [16]:
1 + 1e-12

1.000000000001

In [17]:
1+ 1e-20

1.0

In [18]:
3e34

3e+34

In [19]:
3e34 + 5e28

3.0000050000000002e+34

In [20]:
3e34 + 5e10

3e+34

In [21]:
5e10

50000000000.0

### Período de un péndulo

(ver tarea 3)

### Secuencias numéricas

In [22]:
r = [3,5,8,-23,11]

In [23]:
r

[3, 5, 8, -23, 11]

In [24]:
r = np.array( [3,5,8,-23,11] )  # así mejor para hacer operaciones matemáticas

In [25]:
r

array([  3,   5,   8, -23,  11])

In [26]:
x = np.linspace(3,9,23)

In [27]:
x

array([3.        , 3.27272727, 3.54545455, 3.81818182, 4.09090909,
       4.36363636, 4.63636364, 4.90909091, 5.18181818, 5.45454545,
       5.72727273, 6.        , 6.27272727, 6.54545455, 6.81818182,
       7.09090909, 7.36363636, 7.63636364, 7.90909091, 8.18181818,
       8.45454545, 8.72727273, 9.        ])

In [28]:
y = np.arange(40)

In [29]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [30]:
x

array([3.        , 3.27272727, 3.54545455, 3.81818182, 4.09090909,
       4.36363636, 4.63636364, 4.90909091, 5.18181818, 5.45454545,
       5.72727273, 6.        , 6.27272727, 6.54545455, 6.81818182,
       7.09090909, 7.36363636, 7.63636364, 7.90909091, 8.18181818,
       8.45454545, 8.72727273, 9.        ])

In [31]:
2*x

array([ 6.        ,  6.54545455,  7.09090909,  7.63636364,  8.18181818,
        8.72727273,  9.27272727,  9.81818182, 10.36363636, 10.90909091,
       11.45454545, 12.        , 12.54545455, 13.09090909, 13.63636364,
       14.18181818, 14.72727273, 15.27272727, 15.81818182, 16.36363636,
       16.90909091, 17.45454545, 18.        ])

In [32]:
y-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34])

### Sumatorio

Calcula

$$S = \sum_{k=5}^{22}\left(2k^3-5k^2+3 \right)$$

In [33]:
k = np.arange(5,22+1)

S = np.sum( 2*k**3 - 5*k**2 + 3 )

In [34]:
k

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22])

In [35]:
S

109047

### Reducción de secuencias

Descarga en el directorio de trabajo el archivo situado en http://robot.inf.um.es/material/inforfis/numbers.txt

In [36]:
datos = np.loadtxt('numbers.txt')

In [37]:
datos

array([ 996.,  134.,  932., ...,  -62., -674.,   98.])

In [38]:
np.median(datos)

69.0

In [39]:
np.std(datos)

574.3503337371111

También se puede acceder directamente a la ubicación remota:

In [40]:
otrosdatos = np.loadtxt('http://robot.inf.um.es/material/inforfis/numbers.txt')

In [41]:
np.median(otrosdatos)

69.0